name = "Gosu"
grammar = "gosu"
path_suffixes = ["gs", "gsx", "gsp", "gst", "gosu"]
line_comments = ["// "]
tab_size = 2
autoclose_before = ";:.,=}]) \n\t\"'"
brackets = [
  { start = "{", end = "}", close = true, newline = true },
  { start = "[", end = "]", close = true, newline = false },
  { start = "(", end = ")", close = true, newline = false },
  { start = "\"", end = "\"", close = true, newline = false, not_in = ["string", "comment"] },
  { start = "'", end = "'", close = true, newline = false, not_in = ["string", "comment"] },
  { start = "/*", end = " */", close = true, newline = true, not_in = ["string", "comment"] },
]
collapsed_placeholder = " /* ... */ "
block_comment = { start = "/*", prefix = "", end = "*/", tab_size = 2 }
documentation_comment = { start = "/**", end = "*/", prefix = "* ", tab_size = 1 }
